In [116]:
import tensorflow as tf

In [117]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [118]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None


)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [119]:
print(eye_tensor.ndim)

3


In [120]:
fill_tensor = tf.fill([1,3,4],5)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [121]:
ones_tensor = tf.ones([5,3,2])
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [122]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [123]:
zeros_tensor = tf.zeros([3,2])
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [124]:
tensor_three_d = tf.constant([3,4,5])
tensor_three_d.shape

TensorShape([3])

In [125]:
print(tf.shape(tensor_three_d))

tf.Tensor([3], shape=(1,), dtype=int32)


In [126]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [127]:
print(tf.size(tensor_three_d))

tf.Tensor(3, shape=(), dtype=int32)


In [128]:
t = tf.constant([[1,1,1],[2,2,2],])
print(tf.size(t))

tf.Tensor(6, shape=(), dtype=int32)


In [129]:
random_tensor = tf.random.normal([3,2],mean = 100,stddev=1000,seed= 42)
print(random_tensor,'hiii',tf.reduce_sum((random_tensor)/6)**2)

tf.Tensor(
[[1678.4944  -528.572  ]
 [-819.8288  -372.50598]
 [ 294.9887   654.5166 ]], shape=(3, 2), dtype=float32) hiii tf.Tensor(22856.035, shape=(), dtype=float32)


In [133]:
random_tensor = tf.random.uniform([1,3,4],
                  minval=0,
                  maxval=None,
                  
                  
                  
                  )
print(random_tensor, ' hi ', random_tensor.shape.ndims)

tf.Tensor(
[[[0.3981272  0.10295403 0.50876665 0.34691417]
  [0.09111285 0.6849834  0.24421585 0.9251809 ]
  [0.86569107 0.78432    0.6915451  0.5215851 ]]], shape=(1, 3, 4), dtype=float32)  hi  3
